In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving processed_courses.csv to processed_courses.csv

In [ ]:
courses = pd.read_csv("processed_courses.csv")

In [ ]:
course_kb = courses.groupby(
    ["course_id", "name", "institution"]
).agg(
    average_rating=("rating", "mean"),
    review_count=("rating", "count"),
    reviews=("reviews", lambda x: " ".join(x.astype(str)))
).reset_index()

In [ ]:
course_kb.head()

,course_id,name,institution,average_rating,review_count,reviews
0,aboriginal-education,aboriginal worldviews and education,university of toronto,4.545455,66,this course has great intentions and decent co...
1,access-control-sscp,access controls,(isc)²,4.294118,34,i experienced following problems with the cour...
2,accounting-analytics,accounting analytics,university of pennsylvania,4.354916,417,"first of all, i really enjoyed professor ittne..."
3,accounting-data-analytics-python,accounting data analytics with python,university of illinois at urbana-champaign,3.285714,7,"i enjoyed the course overall and finished, but..."
4,actualizacion-manejo-diabetes-tipo-2,actualización en el manejo del paciente con di...,universidad nacional autónoma de méxico,4.825112,223,no me deja dar mi cerificado y no me puedo com...

In [ ]:
course_kb["reviews"] = course_kb["reviews"].str[:5000]

In [ ]:
course_kb["knowledge"] = (
    "Course Name: " + course_kb["name"] +
    ". Institution: " + course_kb["institution"] +
    ". Average Rating: " + course_kb["average_rating"].round(2).astype(str) +
    ". Number of Reviews: " + course_kb["review_count"].astype(str) +
    ". Reviews: " + course_kb["reviews"]
)

In [ ]:
course_kb[["knowledge"]].head()

                                           knowledge
0  Course Name: aboriginal worldviews and educati...
1  Course Name: access controls. Institution: (is...
2  Course Name: accounting analytics. Institution...
3  Course Name: accounting data analytics with py...
4  Course Name: actualización en el manejo del pa...

In [ ]:
course_kb = course_kb[
    [
        "course_id",
        "name",
        "institution",
        "average_rating",
        "review_count",
        "knowledge"
    ]
]

In [ ]:
course_kb.to_csv("course_knowledge_base.csv", index=False)

In [ ]:
from google.colab import files

files.download("course_knowledge_base.csv")