In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

Saving Coursera_courses.csv to Coursera_courses.csv

In [ ]:
courses = pd.read_csv("Coursera_courses.csv")
courses

,name,institution,course_url,course_id
0,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning
1,Indigenous Canada,University of Alberta,https://www.coursera.org/learn/indigenous-canada,indigenous-canada
2,The Science of Well-Being,Yale University,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being
3,Technical Support Fundamentals,Google,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals
4,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training
...,...,...,...,...
618,Accounting Data Analytics with Python,University of Illinois at Urbana-Champaign,https://www.coursera.org/learn/accounting-data...,accounting-data-analytics-python
619,Introduction to Molecular Spectroscopy,University of Manchester,https://www.coursera.org/learn/spectroscopy,spectroscopy
620,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach
621,The fundamentals of hotel distribution,ESSEC Business School,https://www.coursera.org/learn/hotel-distribution,hotel-distribution
622,A Crash Course in Data Science,Johns Hopkins University,https://www.coursera.org/learn/data-science-co...,data-science-course

In [ ]:
courses.head()

,name,institution,course_url,course_id
0,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning
1,Indigenous Canada,University of Alberta,https://www.coursera.org/learn/indigenous-canada,indigenous-canada
2,The Science of Well-Being,Yale University,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being
3,Technical Support Fundamentals,Google,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals
4,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training

In [ ]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         623 non-null    object
 1   institution  623 non-null    object
 2   course_url   623 non-null    object
 3   course_id    623 non-null    object
dtypes: object(4)
memory usage: 19.6+ KB

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Coursera_reviews.csv to Coursera_reviews.csv

In [ ]:
reviews = pd.read_csv("Coursera_reviews.csv")
reviews

,reviews,reviewers,date_reviews,rating,course_id
0,"Pretty dry, but I was able to pass with just t...",By Robert S,"Feb 12, 2020",4,google-cbrs-cpi-training
1,would be a better experience if the video and ...,By Gabriel E R,"Sep 28, 2020",4,google-cbrs-cpi-training
2,Information was perfect! The program itself wa...,By Jacob D,"Apr 08, 2020",4,google-cbrs-cpi-training
3,A few grammatical mistakes on test made me do ...,By Dale B,"Feb 24, 2020",4,google-cbrs-cpi-training
4,Excellent course and the training provided was...,By Sean G,"Jun 18, 2020",4,google-cbrs-cpi-training
...,...,...,...,...,...
1454706,g,By Brijesh K,"Aug 25, 2020",5,computer-networking
1454707,.,By Vasavi V M,"Jul 02, 2020",5,computer-networking
1454708,.,By Drishti D,"Jun 20, 2020",5,computer-networking
1454709,.,By FAUSTINE F K,"Jun 07, 2020",5,computer-networking
1454710,G,By Reza S,"Aug 12, 2018",5,computer-networking

In [ ]:
merged = pd.merge(
    courses,
    reviews,
    on="course_id",
    how="inner"
)
merged

,name,institution,course_url,course_id,reviews,reviewers,date_reviews,rating
0,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning,This is an extremely basic course. Machine lea...,By Deleted A,"Mar 18, 2017",1
1,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning,The course is ok but the certification procedu...,By Bruno C,"Nov 09, 2015",1
2,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning,"I just started week 3 , I have to admit that I...",By Fadi,"Apr 15, 2019",1
3,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning,This course is absolute garbage. You get no f...,By Mathew L,"Sep 25, 2015",1
4,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning,"However good the material and lectures may be,...",By Rui C,"Dec 12, 2015",1
...,...,...,...,...,...,...,...,...
1454706,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,re,By Sachin M,"Oct 11, 2017",5
1454707,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,E,By Denis,"Mar 10, 2019",5
1454708,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,G,By Neil B,"Oct 13, 2018",5
1454709,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,E,By Isaias M,"Aug 11, 2016",5
1454710,Managing as a Coach,"University of California, Davis",https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,.,By Antonio M,"Feb 21, 2016",5

In [ ]:
courses = courses.drop(columns=["course_url"])

In [ ]:
print(courses.columns.tolist())

['name', 'institution', 'course_id']

In [ ]:
reviews.columns.tolist()

['reviews', 'reviewers', 'date_reviews', 'rating', 'course_id']

In [ ]:
reviews.drop(columns=["reviewers", "date_reviews"], inplace=True)

In [ ]:
reviews.columns.tolist()

['reviews', 'rating', 'course_id']

In [ ]:
merged = pd.merge(
    courses,
    reviews,
    on="course_id",
    how="inner"
)
merged

,name,institution,course_id,reviews,rating
0,Machine Learning,Stanford University,machine-learning,This is an extremely basic course. Machine lea...,1
1,Machine Learning,Stanford University,machine-learning,The course is ok but the certification procedu...,1
2,Machine Learning,Stanford University,machine-learning,"I just started week 3 , I have to admit that I...",1
3,Machine Learning,Stanford University,machine-learning,This course is absolute garbage. You get no f...,1
4,Machine Learning,Stanford University,machine-learning,"However good the material and lectures may be,...",1
...,...,...,...,...,...
1454706,Managing as a Coach,"University of California, Davis",managing-as-a-coach,re,5
1454707,Managing as a Coach,"University of California, Davis",managing-as-a-coach,E,5
1454708,Managing as a Coach,"University of California, Davis",managing-as-a-coach,G,5
1454709,Managing as a Coach,"University of California, Davis",managing-as-a-coach,E,5
1454710,Managing as a Coach,"University of California, Davis",managing-as-a-coach,.,5

In [ ]:
merged.isnull().sum()

name             0
institution      0
course_id        0
reviews        153
rating           0
dtype: int64

In [ ]:
merged.dropna(subset=["reviews"], inplace=True)

In [ ]:
merged.isnull().sum()

name           0
institution    0
course_id      0
reviews        0
rating         0
dtype: int64

In [ ]:
merged.duplicated().sum()

np.int64(953581)

In [ ]:
merged.drop_duplicates(inplace=True)

In [ ]:
merged.duplicated().sum()

np.int64(0)

In [ ]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500977 entries, 0 to 1454700
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   name         500977 non-null  object
 1   institution  500977 non-null  object
 2   course_id    500977 non-null  object
 3   reviews      500977 non-null  object
 4   rating       500977 non-null  int64
dtypes: int64(1), object(4)
memory usage: 22.9+ MB

In [ ]:
#Remove Empty Reviews
merged = merged[
    merged["reviews"].str.len() > 15
]

In [ ]:
text_columns = ["name", "institution", "reviews"]

for col in text_columns:
    merged[col] = (
        merged[col]
        .astype(str)
        .str.lower()
        .str.strip()
    )

/tmp/ipykernel_439/2856972944.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged[col] = (
/tmp/ipykernel_439/2856972944.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged[col] = (
/tmp/ipykernel_439/2856972944.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged[col] = (

In [ ]:
text_columns

['name', 'institution', 'reviews']

In [ ]:
#Remove Extra Spaces
for col in ["name", "institution", "reviews"]:
    merged[col] = merged[col].str.replace(r"\s+", " ", regex=True)

/tmp/ipykernel_439/3511206523.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged[col] = merged[col].str.replace(r"\s+", " ", regex=True)

In [ ]:
merged.drop_duplicates(
    subset=["course_id", "reviews"],
    inplace=True
)

/tmp/ipykernel_439/499243860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged.drop_duplicates(

In [ ]:
merged

,name,institution,course_id,reviews,rating
0,machine learning,stanford university,machine-learning,this is an extremely basic course. machine lea...,1
1,machine learning,stanford university,machine-learning,the course is ok but the certification procedu...,1
2,machine learning,stanford university,machine-learning,"i just started week 3 , i have to admit that i...",1
3,machine learning,stanford university,machine-learning,this course is absolute garbage. you get no fe...,1
4,machine learning,stanford university,machine-learning,"however good the material and lectures may be,...",1
...,...,...,...,...,...
1454568,managing as a coach,"university of california, davis",managing-as-a-coach,great learning!!!,5
1454569,managing as a coach,"university of california, davis",managing-as-a-coach,excellent course.,5
1454570,managing as a coach,"university of california, davis",managing-as-a-coach,good to attempt!!,5
1454621,managing as a coach,"university of california, davis",managing-as-a-coach,excellent course!,5
1454623,managing as a coach,"university of california, davis",managing-as-a-coach,very good course,5

In [ ]:
merged["rating"].value_counts()

rating
5    354819
4     73462
3     16575
1      6161
2      5832
Name: count, dtype: int64

In [ ]:
merged.to_csv("processed_courses.csv", index=False)
merged

,name,institution,course_id,reviews,rating
0,machine learning,stanford university,machine-learning,this is an extremely basic course. machine lea...,1
1,machine learning,stanford university,machine-learning,the course is ok but the certification procedu...,1
2,machine learning,stanford university,machine-learning,"i just started week 3 , i have to admit that i...",1
3,machine learning,stanford university,machine-learning,this course is absolute garbage. you get no fe...,1
4,machine learning,stanford university,machine-learning,"however good the material and lectures may be,...",1
...,...,...,...,...,...
1454568,managing as a coach,"university of california, davis",managing-as-a-coach,great learning!!!,5
1454569,managing as a coach,"university of california, davis",managing-as-a-coach,excellent course.,5
1454570,managing as a coach,"university of california, davis",managing-as-a-coach,good to attempt!!,5
1454621,managing as a coach,"university of california, davis",managing-as-a-coach,excellent course!,5
1454623,managing as a coach,"university of california, davis",managing-as-a-coach,very good course,5

In [ ]:
from google.colab import files

files.download("processed_courses.csv")